# Generated by Django 2.2.6 on 2019-10-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('request_time', models.DurationField(blank=True, null=True)),
                ('number_of_queries', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
