# Generated by Django 2.2.6 on 2019-10-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='request_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
