# Generated by Django 2.2.6 on 2019-11-14 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191015_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('brand', models.CharField(blank=True, max_length=1000, null=True)),
                ('category_level_1', models.CharField(blank=True, max_length=1000, null=True)),
                ('variations', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.FloatField()),
                ('profit', models.FloatField()),
                ('last_month_sales', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
